-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GEN AS (
    -- 1세대: 부모가 없는 개체
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 자식 세대: 부모 세대 + 1
    SELECT
        E.ID,
        E.PARENT_ID,
        G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN ECOLI_GEN G
        ON E.PARENT_ID = G.ID
)

SELECT
    COUNT(*) AS COUNT,
    G.GENERATION
FROM ECOLI_GEN G
LEFT JOIN ECOLI_DATA C
    ON G.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;