-- 코드를 작성해주세요
SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_NAME_INFO N
JOIN FISH_INFO F ON F.FISH_TYPE = N.FISH_TYPE
WHERE F.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO I WHERE I.FISH_TYPE = N.FISH_TYPE)
ORDER BY F.ID ASC